apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
#  volumes:
#  - name: mysql-storage
#    hostPath:
#      path: /var/kube-test/mysql-db
  containers:
  - name: mysql
    image: mysql
#    volumeMounts:
#    - name: mysql-storage
#      mountPath: /var/lib/mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
